// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJ3o7iGZ8T9ysyN6IeZ7zi2L7MAnNelU',
    appId: '1:227613701589:web:e2eb4e68ab97b14a10b95c',
    messagingSenderId: '227613701589',
    projectId: 'seasonanimation',
    authDomain: 'seasonanimation.firebaseapp.com',
    storageBucket: 'seasonanimation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHgqxEcKaaWRl4wzciyQOveloH6hPi5w',
    appId: '1:227613701589:android:47060c581a42b99e10b95c',
    messagingSenderId: '227613701589',
    projectId: 'seasonanimation',
    storageBucket: 'seasonanimation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPK4OHmIOp3vAcI1EQ9DUCcZtbT8lqnlw',
    appId: '1:227613701589:ios:ccb1860b59325a7710b95c',
    messagingSenderId: '227613701589',
    projectId: 'seasonanimation',
    storageBucket: 'seasonanimation.firebasestorage.app',
    iosBundleId: 'com.example.funAnimation',
  );

}